# Generated by Django 5.0.6 on 2024-06-19 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0036_alter_order_odatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 19, 22, 35, 12, 235166)),
        ),
    ]
